### ISSUE TITLE
Windows Compatability??

### ISSUE THREAD

**Issue by ayunami2000** [jmptable/calc_control#1]
Is this a possibility? If not, is it possible to run using WSL (Windows Subsystem for Linux)?

**Comment by jmpinit** [comment]
The example Ruby scripts should run fine on Windows but I haven't tried running them in a very long time.

**Comment by ayunami2000** [comment]
one of them references "/dev/ttyUSB0" which i believe is a linux thing, but correct me if I'm wrong bc I do not know Ruby
https://github.com/jmptable/calc_control/blob/master/examples/type-text/type-text.rb

**Comment by jmpinit** [comment]
You are correct, normally serial devices are referred to by file path on Linux and by COM port on Windows. Replacing that path with the COM name of your serial port (e.g. COM4) should make it work on Windows.

**Comment by ayunami2000** [comment]
ah ok, thank you!
